<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(
    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'QCM\Controller\Question' => 'QCM\Controller\QuestionController',
            'QCM\Controller\Answer' => 'QCM\Controller\AnswerController',
        ),
    ),

    'service_manager' => array(

    ),

    'router' => array(
// Uncomment below to add routes
        'routes' => array(
            'qcm' => array(
                'type' => 'Segment',
                'options' => array(
                    'route'    => '/qcm[/:action][/:id]',
                    'constraints' => array(
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'id'     => '[0-9]+',
                    ),
                    'defaults' => array(
                        'controller' => 'QCM\Controller\Question',
                        'action'     => 'index',
                    ),
                ),
            ),
            'answer' => array(
                'type' => 'Segment',
                'options' => array(
                    'route'    => '/qcm/question/:idQuestion[/:action][/:id]',
                    'constraints' => array(
                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'idQuestion' => '[0-9]+',
                        'id' => '[0-9]+',
                    ),
                    'defaults' => array(
                        'controller' => 'QCM\Controller\Answer',
                        'action'     => 'index',
                        'idQuestion' => 0,
                    ),
                ),
            ),
        ),

    )
);