<?php
 // module/Album/view/album/album/delete.phtml:

 $title = 'Answer a question';
 $this->headTitle($title);

 $url = $this->url('qcm', array(
     'action' => 'answer',
     'id'     => $this->id,
 ));
 ?>

<div class="mdl-card mdl-shadow--6dp">
    <form action="<?php echo $url; ?>" method="post">
        <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
            <h2 class="mdl-card__title-text"><?php echo $this->escapeHtml($question->title); ?></h2>
        </div>
        <div class="mdl-card__supporting-text">
            <?php foreach ($answers as $answer) : ?>
            <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for='option-<?php echo $answer->id; ?>'>
                <input type="radio" id='option-<?php echo $answer->id; ?>' class="mdl-radio__button" name="options" value='<?php echo $answer->id; ?>' checked>
                <span class="mdl-radio__label"><?php echo $answer->title; ?></span>
            </label>
                <br>
            <?php endforeach; ?>
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <input type="hidden" name="id" value="<?php echo (int) $question->id; ?>" />
            <button class="mdl-button mdl-js-button mdl-button--icon mdl-button--accent" value="Yes" type="submit" name="del">
                <i class="material-icons">check</i>
            </button>
            <button class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored" value="No" type="submit" name="del">
                <i class="material-icons">clear</i>
            </button>
        </div>
    </form>
</div>