<?php
// module/Album/view/album/album/index.phtml:

$title = 'Questions';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
    <thead>
        <tr>
            <th class="mdl-data-table__cell--non-numeric">Title</th>
            <th class="mdl-data-table__cell--non-numeric">Artist</th>
            <th class="mdl-data-table__cell--non-numeric">Action</th>
        </tr>
    </thead>

    <tbody>
    <?php
    /** @var array $questions */
    foreach ($questions as $question) : ?>
        <tr>
            <td class="mdl-data-table__cell--non-numeric"><?php echo $this->escapeHtml($question->title);?></td>
            <td class="mdl-data-table__cell--non-numeric">
                <button class="mdl-button mdl-js-button mdl-button--primary" onclick="location.href='<?php echo $this->url('album',
                    array('action'=>'edit', 'id' => $question->idQuestion));?>'">
                    Edit
                </button>
                <button class="mdl-button mdl-js-button mdl-button--accent" onclick="location.href='<?php echo $this->url('album',
                    array('action'=>'delete', 'id' => $question->idQuestion));?>'">
                    Delete
                </button>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--2dp" onclick="location.href='<?php echo $this->url('album', array('action'=>'add'));?>'">
    <i class="material-icons">add</i>
</button>