<?php
 // module/Album/view/album/album/delete.phtml:

 $title = 'Delete answer';
 $this->headTitle($title);

 $url = $this->url('answer', array(
     'action' => 'delete',
     'id'     => $this->id,
     'idQuestion'     => $this->idQuestion,
 ));
 ?>

<div class="mdl-card mdl-shadow--6dp">
    <form action="<?php echo $url; ?>" method="post">
        <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
            <h2 class="mdl-card__title-text"><?php echo $this->escapeHtml($title); ?></h2>
        </div>
        <div class="mdl-card__supporting-text">
            <p>Are you sure that you want to delete
                '<?php echo $this->escapeHtml($answer->title); ?>'?
            </p>
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <input type="hidden" name="id" value="<?php echo (int) $answer->id; ?>" />
            <button class="mdl-button mdl-js-button mdl-button--icon mdl-button--accent" value="Yes" type="submit" name="del">
                <i class="material-icons">check</i>
            </button>
            <button class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored" value="No" type="submit" name="del">
                <i class="material-icons">clear</i>
            </button>
        </div>
    </form>
</div>