<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->headLink(array('rel' => 'stylesheet', 'href' => 'https://storage.googleapis.com/code.getmdl.io/1.0.6/material.indigo-pink.min.css'))
                        ->headLink(array('rel' => 'stylesheet', 'href' => 'https://fonts.googleapis.com/icon?family=Material+Icons'))
                        ->headLink(array('rel' => 'stylesheet', 'type' => 'text/css', 'href' => 'http://fonts.googleapis.com/css?family=Roboto:300,400,500,700'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile('https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js')
        ; ?>

    </head>
    <body>
        <div class="mdl-layout mdl-js-layout mdl-color--grey-100">
            <header class="mdl-layout__header">
                <div class="mdl-layout-icon"></div>
                <div class="mdl-layout__header-row">
                    <span class="mdl-layout__title"><?php echo $this->translate('Skeleton Application') ?></span>
                    <div class="mdl-layout-spacer"></div>
                    <nav class="mdl-navigation">
                        <a class="mdl-navigation__link" href="/">Home</a>
                        <?php
                        if($this->layout()->connected){
                            ?>
                            <a class="mdl-navigation__link" href="/application/logout">Déconnexion</a>
                        <?php
                        } else {
                            ?>
                            <a class="mdl-navigation__link" href="/application/login">Connexion</a>
                            <a class="mdl-navigation__link" href="/application/signup">Inscription</a>
                        <?php
                        }
                        ?>
                    </nav>
                </div>
            </header>
            <main class="mdl-layout__content">
                <?php echo $this->content; ?>
            </main>
            <footer class="mdl-mini-footer">
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
            <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
